// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qewznpnmaqhqfyhncdnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFld3pucG5tYXFocWZ5aG5jZG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTg4NTcsImV4cCI6MjA2OTM5NDg1N30.6D7IL0c2AuBsfNGEUzHpIDvhwVw65hz-jQVyAxhRkEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});