// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyrvxikgtifklibusxwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cnZ4aWtndGlma2xpYnVzeHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTMxMDMsImV4cCI6MjA3MTc4OTEwM30.TyW35cWoe9EvF2hCpQ-di4lGDZeWc0yIU80EZmC1Vnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});